In [1]:
# Initial imports
import pandas as pd
import numpy as np
from pathlib import Path
from keras.models import Sequential
from keras.layers import Dense, Activation

In [2]:
# Loading data
file_path = Path("../Datasets/1dayForward/algoData_gold_1dayForward_Modified2.csv")
df = pd.read_csv(file_path)

In [3]:
# Generate the categorical outcome variable
df['outcome'] = np.nan
df.loc[(df['Signal']==1), 'outcome'] = 'Buy'
df.loc[(df['Signal']==-1), 'outcome'] = 'Sell'

In [4]:
# Preview the output variable 
y = df['Signal']

# Save the unique number of labels for future use
number_of_classes = len(list(y.drop_duplicates()))

# Specify X (predictor) variables
X = df.drop(columns=["Signal", "outcome"])

In [5]:
# Encode earnings labels to integers
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(y)
encoded_y = encoder.transform(y)

In [6]:
# Convert labeled integers to a Keras `categorical` data type
from keras.utils.np_utils import to_categorical
y_categorical = to_categorical(encoded_y, num_classes=number_of_classes)

In [7]:
# Split into training and testing windows
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y_categorical, random_state=42, stratify=y)

X_train = X.loc[:3000]
X_test = X.loc[3001:]

y_train = y.loc[:3000]
y_test = y.loc[3001:]

In [8]:
# Build the neural network layers

number_of_predictors = len(X.columns)
hidden_nodes_layer1 = 120
hidden_nodes_layer2 = 100

model = Sequential()
model.add(Dense(hidden_nodes_layer1, input_dim=number_of_predictors, activation='relu'))
model.add(Dense(hidden_nodes_layer2, activation='relu'))

In [9]:
# Add the final output layer
# With the # of possible outputs equal to the number classes 
model.add(Dense(1, activation='tanh'))

In [10]:
# Compile the model (with multi-class specific parameters)
model.compile(loss= "binary_crossentropy", 
              optimizer= "adam", 
              metrics=['binary_accuracy'])

In [11]:
y_train = y_train.values.reshape(-1,1)

In [12]:
#X_train

In [13]:
from sklearn.preprocessing import StandardScaler
# Create scaler instance
X_scaler = StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
#X_train_scaled.shape

In [15]:
#y_train.shape

In [16]:
X_train_scaled

array([[ 0.03297458, -0.9019597 , -1.26507132, ..., -0.16299913,
        -0.02845636, -0.21957217],
       [ 0.57250984, -0.73826472, -1.15260593, ...,  0.03344131,
         0.2093924 , -0.16521965],
       [ 1.83349493, -0.30496737, -0.82781827, ...,  0.51488988,
         0.73602387,  0.02606076],
       ...,
       [-0.21925587,  0.26467346,  0.004183  , ...,  0.57074778,
         0.45598682,  0.40064644],
       [-0.52654704,  0.11156384, -0.07917809, ...,  0.35586934,
         0.10981987,  0.43003297],
       [ 0.31034754, -0.18630084, -0.28066107, ..., -0.00617867,
        -0.34244904,  0.34425623]])

In [17]:
y_train

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [-1],
       [-1],
       [ 1]], dtype=int64)

In [18]:
# Summarise the structure of the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 120)               1800      
                                                                 
 dense_1 (Dense)             (None, 100)               12100     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 14,001
Trainable params: 14,001
Non-trainable params: 0
_________________________________________________________________


In [19]:
# Fit the model
model.fit(X_train_scaled,y_train, 
                    epochs=500,
                    batch_size=500,
                    shuffle=False)

Epoch 1/500
7/7 [==============================] - 0s 2ms/step - loss: 1.2365 - binary_accuracy: 0.0170
Epoch 2/500
7/7 [==============================] - 0s 2ms/step - loss: -1.4759 - binary_accuracy: 0.0277
Epoch 3/500
7/7 [==============================] - 0s 3ms/step - loss: -2.3588 - binary_accuracy: 0.0380
Epoch 4/500
7/7 [==============================] - 0s 2ms/step - loss: -3.0623 - binary_accuracy: 0.0400
Epoch 5/500
7/7 [==============================] - 0s 3ms/step - loss: -4.0040 - binary_accuracy: 0.0663
Epoch 6/500
7/7 [==============================] - 0s 2ms/step - loss: -4.9456 - binary_accuracy: 0.1110
Epoch 7/500
7/7 [==============================] - 0s 3ms/step - loss: -4.7701 - binary_accuracy: 0.1869
Epoch 8/500
7/7 [==============================] - 0s 3ms/step - loss: -4.6884 - binary_accuracy: 0.2089
Epoch 9/500
7/7 [==============================] - 0s 2ms/step - loss: -4.2326 - binary_accuracy: 0.1716
Epoch 10/500
7/7 [==============================] - 0s 2

7/7 [==============================] - 0s 3ms/step - loss: -6.7552 - binary_accuracy: 0.4212
Epoch 79/500
7/7 [==============================] - 0s 2ms/step - loss: -6.7979 - binary_accuracy: 0.4249
Epoch 80/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8787 - binary_accuracy: 0.4259
Epoch 81/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8741 - binary_accuracy: 0.4162
Epoch 82/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8281 - binary_accuracy: 0.4102
Epoch 83/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8202 - binary_accuracy: 0.4175
Epoch 84/500
7/7 [==============================] - 0s 2ms/step - loss: -6.1366 - binary_accuracy: 0.4575
Epoch 85/500
7/7 [==============================] - 0s 2ms/step - loss: -5.7154 - binary_accuracy: 0.4528
Epoch 86/500
7/7 [==============================] - 0s 3ms/step - loss: -5.5944 - binary_accuracy: 0.4449
Epoch 87/500
7/7 [==============================] - 0s 2ms/

7/7 [==============================] - 0s 3ms/step - loss: -7.0501 - binary_accuracy: 0.4595
Epoch 155/500
7/7 [==============================] - 0s 3ms/step - loss: -7.0467 - binary_accuracy: 0.4618
Epoch 156/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0829 - binary_accuracy: 0.4558
Epoch 157/500
7/7 [==============================] - 0s 3ms/step - loss: -7.0834 - binary_accuracy: 0.4542
Epoch 158/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0879 - binary_accuracy: 0.4558
Epoch 159/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0221 - binary_accuracy: 0.4479
Epoch 160/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8560 - binary_accuracy: 0.4245
Epoch 161/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8271 - binary_accuracy: 0.4229
Epoch 162/500
7/7 [==============================] - 0s 2ms/step - loss: -6.8820 - binary_accuracy: 0.4262
Epoch 163/500
7/7 [==============================] 

7/7 [==============================] - 0s 2ms/step - loss: -5.6811 - binary_accuracy: 0.5072
Epoch 231/500
7/7 [==============================] - 0s 2ms/step - loss: -5.8022 - binary_accuracy: 0.5045
Epoch 232/500
7/7 [==============================] - 0s 3ms/step - loss: -6.0926 - binary_accuracy: 0.5012
Epoch 233/500
7/7 [==============================] - 0s 2ms/step - loss: -6.2719 - binary_accuracy: 0.4992
Epoch 234/500
7/7 [==============================] - 0s 4ms/step - loss: -6.4061 - binary_accuracy: 0.4945
Epoch 235/500
7/7 [==============================] - 0s 2ms/step - loss: -6.5278 - binary_accuracy: 0.4905
Epoch 236/500
7/7 [==============================] - 0s 3ms/step - loss: -6.5956 - binary_accuracy: 0.4905
Epoch 237/500
7/7 [==============================] - 0s 2ms/step - loss: -6.6784 - binary_accuracy: 0.4952
Epoch 238/500
7/7 [==============================] - 0s 3ms/step - loss: -6.7442 - binary_accuracy: 0.4958
Epoch 239/500
7/7 [==============================] 

7/7 [==============================] - 0s 3ms/step - loss: -6.9515 - binary_accuracy: 0.4782
Epoch 307/500
7/7 [==============================] - 0s 2ms/step - loss: -6.9712 - binary_accuracy: 0.4815
Epoch 308/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0072 - binary_accuracy: 0.4892
Epoch 309/500
7/7 [==============================] - 0s 2ms/step - loss: -6.9815 - binary_accuracy: 0.4915
Epoch 310/500
7/7 [==============================] - 0s 2ms/step - loss: -6.9971 - binary_accuracy: 0.4905
Epoch 311/500
7/7 [==============================] - 0s 3ms/step - loss: -7.0056 - binary_accuracy: 0.4912
Epoch 312/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0142 - binary_accuracy: 0.4902
Epoch 313/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0459 - binary_accuracy: 0.4888
Epoch 314/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0678 - binary_accuracy: 0.4865
Epoch 315/500
7/7 [==============================] 

7/7 [==============================] - 0s 3ms/step - loss: -7.0919 - binary_accuracy: 0.4785
Epoch 383/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0951 - binary_accuracy: 0.4802
Epoch 384/500
7/7 [==============================] - 0s 3ms/step - loss: -7.1175 - binary_accuracy: 0.4825
Epoch 385/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0828 - binary_accuracy: 0.4845
Epoch 386/500
7/7 [==============================] - 0s 2ms/step - loss: -7.0353 - binary_accuracy: 0.4865
Epoch 387/500
7/7 [==============================] - 0s 2ms/step - loss: -7.1056 - binary_accuracy: 0.4822
Epoch 388/500
7/7 [==============================] - 0s 3ms/step - loss: -7.1395 - binary_accuracy: 0.4765
Epoch 389/500
7/7 [==============================] - 0s 2ms/step - loss: -7.1330 - binary_accuracy: 0.4745
Epoch 390/500
7/7 [==============================] - 0s 3ms/step - loss: -7.1324 - binary_accuracy: 0.4745
Epoch 391/500
7/7 [==============================] 

7/7 [==============================] - 0s 3ms/step - loss: -7.2813 - binary_accuracy: 0.4938
Epoch 459/500
7/7 [==============================] - 0s 3ms/step - loss: -7.2283 - binary_accuracy: 0.4908
Epoch 460/500
7/7 [==============================] - 0s 2ms/step - loss: -6.7923 - binary_accuracy: 0.4485
Epoch 461/500
7/7 [==============================] - 0s 2ms/step - loss: -6.5275 - binary_accuracy: 0.4325
Epoch 462/500
7/7 [==============================] - 0s 3ms/step - loss: -6.4095 - binary_accuracy: 0.4215
Epoch 463/500
7/7 [==============================] - 0s 3ms/step - loss: -6.4839 - binary_accuracy: 0.4292
Epoch 464/500
7/7 [==============================] - 0s 3ms/step - loss: -6.6361 - binary_accuracy: 0.4465
Epoch 465/500
7/7 [==============================] - 0s 3ms/step - loss: -6.6180 - binary_accuracy: 0.4588
Epoch 466/500
7/7 [==============================] - 0s 2ms/step - loss: -6.6800 - binary_accuracy: 0.4685
Epoch 467/500
7/7 [==============================] 

In [20]:
# Evaluate model on the test data
model.evaluate(X_test_scaled,y_test, verbose=2)

33/33 - 0s - loss: -5.6703e+00 - binary_accuracy: 0.4379 - 166ms/epoch - 5ms/step


[-5.670301914215088, 0.43792107701301575]

In [21]:
# Save predictions on the test data
predictions = model.predict(X_test_scaled).astype('float32')
#predictions = model.predict(X_test_scaled)

33/33 [==============================] - 0s 777us/step


In [23]:
predictions[0]

array([-0.9920743], dtype=float32)

In [24]:
count = len(predictions)

test_predictions = []

for i in range(0,count):
    if(predictions[i] < 0):
        test_predictions.append(-1)
    else:
        test_predictions.append(1)


In [46]:
count

1039

In [47]:
X_test.shape

(1039, 14)

In [70]:
c = np.array(test_predictions)

In [71]:
d = c.reshape(-1,1)

In [72]:
d

array([[-1],
       [ 1],
       [ 1],
       ...,
       [-1],
       [-1],
       [-1]])

In [48]:
data2 = {'Returns': X_test['ActualReturns'], 'Predictions': test_predictions}

In [49]:
gold = pd.DataFrame(data1)

ValueError: All arrays must be of the same length

In [53]:
data.flatten()

AttributeError: 'dict' object has no attribute 'flatten'

In [82]:
test = X_test['ActualReturns']

In [83]:
test['predictions'] = test_predictions

C:\Users\desig\AppData\Local\Temp\ipykernel_30404\3469833111.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predictions'] = test_predictions


In [84]:
test

3001                                                   -0.002417
3002                                                    0.004512
3003                                                    0.003327
3004                                                    -0.00829
3005                                                    0.002592
                                     ...                        
4036                                                    0.006776
4037                                                   -0.001983
4038                                                   -0.012705
4039                                                   -0.002257
predictions    [-1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1,...
Name: ActualReturns, Length: 1040, dtype: object

In [75]:
test['predictions'] = d

C:\Users\desig\AppData\Local\Temp\ipykernel_30404\2099486726.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predictions'] = d


In [85]:
test.to_csv('check.csv')

In [78]:
del test

In [51]:
a = X_test['ActualReturns'].flatten()

AttributeError: 'Series' object has no attribute 'flatten'

In [80]:
test_predictions

[-1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,

In [61]:
test_predictions.reshape(-1,1)

AttributeError: 'list' object has no attribute 'reshape'

In [29]:
returns = X_test['ActualReturns'].values.reshape(-1,1)

In [30]:
returns

array([[-0.00241719],
       [ 0.00451195],
       [ 0.00332723],
       ...,
       [-0.0019832 ],
       [-0.01270547],
       [-0.00225662]])

In [28]:
predictions

array([[-0.9920743 ],
       [ 0.9985946 ],
       [ 0.9834382 ],
       ...,
       [-0.98766065],
       [-0.99999964],
       [-0.97590375]], dtype=float32)

In [ ]:
# Get the most likely prediction for each observation
most_likely = np.argmax(predictions, axis=1)
#most_likely

results = most_likely

In [ ]:
results

NameError: name 'a' is not defined

In [ ]:
# Convert most likely category back to original labels
most_likely = encoder.inverse_transform((most_likely))
#most_likely

In [ ]:
# Evaluate prediction balance
#pd.DataFrame(most_likely).value_counts()

In [ ]:
from sklearn.metrics import classification_report

y_test_mod = []
count = len(y_test)

for i in range(0, count):
    if(y_test[i][0]==1):
        y_test_mod.append(0)
    else:
        y_test_mod.append(1)
        
test_results = np.array(y_test_mod)

print("Classification Report")
print(classification_report(test_results, results))